In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('titanic.csv')
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
label = dataset['Survived']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(dataset, label, train_size=0.7, test_size=0.3)

In [8]:
Y_train

283    1
817    0
451    0
141    1
856    1
      ..
308    0
712    1
94     0
803    1
489    1
Name: Survived, Length: 623, dtype: int64

In [9]:
Y_test

19     1
587    1
552    0
497    0
554    1
      ..
569    1
708    1
58     1
503    0
215    1
Name: Survived, Length: 268, dtype: int64

In [10]:
train_data = X_train[['Sex', 'Age', 'Pclass', 'Fare']]
train_data

Sex    Age  Pclass      Fare
283    male  19.00       3    8.0500
817    male  31.00       2   37.0042
451    male    NaN       3   19.9667
141  female  22.00       3    7.7500
856  female  45.00       1  164.8667
..      ...    ...     ...       ...
308    male  30.00       2   24.0000
712    male  48.00       1   52.0000
94     male  59.00       3    7.2500
803    male   0.42       3    8.5167
489    male   9.00       3   15.9000

[623 rows x 4 columns]

In [ ]:
# train_label = X_train[['Survived']]
# train_label

In [11]:
test_data = X_test[['Sex', 'Age', 'Pclass', 'Fare']]
test_data

Sex   Age  Pclass      Fare
19   female   NaN       3    7.2250
587    male  60.0       1   79.2000
552    male   NaN       3    7.8292
497    male   NaN       3   15.1000
554  female  22.0       3    7.7750
..      ...   ...     ...       ...
569    male  32.0       3    7.8542
708  female  22.0       1  151.5500
58   female   5.0       2   27.7500
503  female  37.0       3    9.5875
215  female  31.0       1  113.2750

[268 rows x 4 columns]

In [12]:
# test_label = X_test[['Survived']]
# test_label

In [13]:
mean = train_data["Age"].mean()
mean

30.080483870967743

In [14]:
train_data["Age"]= train_data["Age"].replace(np.nan, mean)

<ipython-input-14-9e4dcb176a41>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data["Age"]= train_data["Age"].replace(np.nan, mean)


In [15]:
train_data

Sex        Age  Pclass      Fare
283    male  19.000000       3    8.0500
817    male  31.000000       2   37.0042
451    male  30.080484       3   19.9667
141  female  22.000000       3    7.7500
856  female  45.000000       1  164.8667
..      ...        ...     ...       ...
308    male  30.000000       2   24.0000
712    male  48.000000       1   52.0000
94     male  59.000000       3    7.2500
803    male   0.420000       3    8.5167
489    male   9.000000       3   15.9000

[623 rows x 4 columns]

In [ ]:
mean2 = test_data["Age"].mean()
mean2

In [16]:
test_data["Age"]= test_data["Age"].replace(np.nan, 0)

<ipython-input-16-f4888511d392>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data["Age"]= test_data["Age"].replace(np.nan, 0)


In [17]:
test_data

Sex   Age  Pclass      Fare
19   female   0.0       3    7.2250
587    male  60.0       1   79.2000
552    male   0.0       3    7.8292
497    male   0.0       3   15.1000
554  female  22.0       3    7.7750
..      ...   ...     ...       ...
569    male  32.0       3    7.8542
708  female  22.0       1  151.5500
58   female   5.0       2   27.7500
503  female  37.0       3    9.5875
215  female  31.0       1  113.2750

[268 rows x 4 columns]

In [18]:
def min_max_scaling(data):
    
    data_norm = data.copy()
    
    for column in data_norm.columns:
        data_norm[column] = (data_norm[column] - data_norm[column].min()) / (data_norm[column].max() - data_norm[column].min())
        
    return data_norm

In [19]:
norm_train_data = min_max_scaling(train_data[['Age', 'Fare']])

In [20]:
norm_train_data

Age      Fare
283  0.233476  0.015713
817  0.384267  0.072227
451  0.372713  0.038972
141  0.271174  0.015127
856  0.560191  0.321798
..        ...       ...
308  0.371701  0.046845
712  0.597889  0.101497
94   0.736115  0.014151
803  0.000000  0.016623
489  0.107816  0.031035

[623 rows x 2 columns]

In [21]:
norm_test_data = min_max_scaling(test_data[['Age', 'Fare']])

In [22]:
norm_test_data

Age      Fare
19   0.000000  0.014102
587  0.810811  0.154588
552  0.000000  0.015282
497  0.000000  0.029473
554  0.297297  0.015176
..        ...       ...
569  0.432432  0.015330
708  0.297297  0.295806
58   0.067568  0.054164
503  0.500000  0.018714
215  0.418919  0.221098

[268 rows x 2 columns]

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
kNN=KNeighborsClassifier(n_neighbors=3, weights='distance')

In [25]:
kNN.fit(norm_train_data, Y_train)
class_result = kNN.predict(norm_test_data)
class_result

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1], dtype=int64)

In [26]:
precision_ratio=kNN.score(norm_test_data, Y_test)

In [27]:
error_ratio=1-precision_ratio

In [28]:
error_ratio

0.4253731343283582

In [29]:
from sklearn.model_selection import KFold

In [30]:
mean3 = dataset["Age"].mean()
dataset["Age"]= dataset["Age"].replace(np.nan, mean3)
dataset3 = min_max_scaling(dataset[['Age', 'Fare']])

In [31]:
kf=KFold(n_splits=10, shuffle=False)
print(kf) 

KFold(n_splits=10, random_state=None, shuffle=False)


In [32]:
X_train = []
X_test = []
Y_train = []
Y_test = []
X = np.array(dataset[['Age', 'Fare']])
Y = np.array(label)

In [33]:
for train_index, test_index in kf.split(X):
    X_train.append(X[train_index])
    X_test.append(X[test_index])
    Y_train.append(Y[train_index])
    Y_test.append(Y[test_index])

In [34]:
X_train = np.array(X_train[0])
X_test = np.array(X_test[0])
Y_train = np.array(Y_train[0])
Y_test = np.array(Y_test[0])

In [35]:
kNN=KNeighborsClassifier(n_neighbors=3, weights='distance')

In [36]:
kNN.fit(X_train, Y_train)
class_result = kNN.predict(X_test)
class_result

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0], dtype=int64)

In [37]:
precision_ratio=kNN.score(X_test, Y_test)

In [38]:
error_ratio=1-precision_ratio

In [39]:
error_ratio

0.4555555555555556

In [40]:
from sklearn.model_selection import LeaveOneOut

In [41]:
loo = LeaveOneOut()

In [42]:
loo.get_n_splits(X)

891

In [43]:
X_train2 = []
X_test2 = []
Y_test2 = []
X2 = np.array(dataset[['Age', 'Fare']])
Y2 = np.array(label)

In [44]:
for train_index, test_index in loo.split(X):
    X_train2 = X2[train_index]
    
    temp2 = X2[test_index]
    X_test2.append(temp2[0])
    Y_train2 = Y2[train_index]
    
    temp = Y2[test_index]
    Y_test2.append(temp[0])

In [45]:
X_test2 = np.array(X_test2)
Y_test2 = np.array(Y_test2)

In [46]:
kNN=KNeighborsClassifier(n_neighbors=3, weights='distance')

In [47]:
kNN.fit(X_train2, Y_train2)
class_result = kNN.predict(X_test2)
class_result

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,

In [48]:
precision_ratio=kNN.score(X_test2, Y_test2)

In [49]:
error_ratio=1-precision_ratio

In [50]:
error_ratio

0.0505050505050505